#!/bin/zsh
export PS1="\e[32;1m\W \$ \e[0m"
export PATH="$PATH:/Applications/Visual\ Studio\ Code.app/Contents/MacOS/:/opt/homebrew/opt/mysql@5.7/bin"
alias python='python3'
alias pip="pip3"
alias vim="nvim"
alias ll="ls -l"
alias ipython="python -m IPython"
alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
eval "$(rbenv init -)"
export JAVA_HOME=`/usr/libexec/java_home -v 21`
export PATH="~/.npm-global/bin:$PATH"
